language: node_js
sudo: false
node_js:
  - 12

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

deploy:
  - provider: npm
    skip_cleanup: true
    on:
      tags: true
    email: 502532346@qq.com
    api_key: "$NPM_TOKEN"
